manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-behavior-simple-layer
      path: modules/zmk-behavior-simple-layer
      url: https://github.com/urob/zmk-behavior-simple-layer
      revision: main

  self:
    path: config
